import { BlackjackEngine, normalizedTC, total } from './src/engine.js';
import { loadBankroll, saveBankroll, saveSnapshot, loadSnapshot, clearSnapshot } from './src/persistence.js';
import * as THREE from './vendor/three.module.js';
import { CSS3DRenderer, CSS3DObject } from './vendor/CSS3DRenderer.js';

const $ = s => document.querySelector(s), signed = n => n > 0 ? `+${n}` : String(n);
const emptyStats = () => ({ asked: 0, correct: 0, history: [] });
let money = loadBankroll() || { bankroll: 1000, netProfit: 0, lastRoundNet: 0, ledger: [] };
money.sessionId ||= `session-${Date.now()}-${Math.random().toString(36).slice(2)}`;
money.roundSerial ||= 0;
let stats = emptyStats();
try { const s = JSON.parse(localStorage.getItem('opp-trainer-stats')); if (s && Number.isFinite(s.asked) && Array.isArray(s.history)) stats = s; } catch {}
const restored = loadSnapshot();
let engine = restored?.engine || new BlackjackEngine({ decks: 6, initialBankroll: money.bankroll });
if (!restored) { engine.bankroll = money.bankroll; engine.netProfit = money.netProfit; }
let quizTarget = restored?.quizTarget || null, graded = restored?.graded || false;
if (restored?.stats) stats = restored.stats;

const animation = { scene: new THREE.Scene(), camera: new THREE.PerspectiveCamera(38, 1, 1, 3000), renderer: new CSS3DRenderer(), active: new Set(), animated: new Set(), hidden: new Map() };
function initThree() { const host = $('#three-table'); animation.renderer.domElement.setAttribute('aria-hidden', 'true'); host.append(animation.renderer.domElement); resizeThree(); window.addEventListener('resize', resizeThree, { passive: true }); }
function resizeThree() { const w = innerWidth, h = innerHeight; animation.camera.aspect = w / h; animation.camera.position.z = h / (2 * Math.tan(THREE.MathUtils.degToRad(38) / 2)); animation.camera.updateProjectionMatrix(); animation.renderer.setSize(w, h); animation.renderer.render(animation.scene, animation.camera); }
function cardElement(card, revealed = !card.hidden) { const el = document.createElement('div'); el.className = `card ${['♥','♦'].includes(card.suit) ? 'red' : ''}${revealed ? '' : ' hidden-card'}`; el.dataset.cardId = card.id; el.innerHTML = revealed ? `<span class="rank">${card.rank === 'T' ? '10' : card.rank}</span><span class="suit">${card.suit}</span>` : '<span class="back-mark">♠</span>'; return el; }
function animateClone(card, target, reveal) {
  if (matchMedia('(prefers-reduced-motion: reduce)').matches || animation.active.has(card.id)) return;
  const rect = target.getBoundingClientRect(), clone = cardElement(card, !card.hidden && !reveal), object = new CSS3DObject(clone), start = performance.now(), from = new THREE.Vector3(0, innerHeight / 2, -120), to = new THREE.Vector3(rect.left + rect.width / 2 - innerWidth / 2, -(rect.top + rect.height / 2 - innerHeight / 2), 0);
  clone.style.width = `${rect.width}px`; clone.style.height = `${rect.height}px`; clone.style.pointerEvents = 'none'; target.style.opacity = '0'; animation.active.add(card.id); animation.scene.add(object); object.position.copy(from); if (reveal) object.rotation.y = Math.PI;
  const tick = now => { const t = Math.min(1, (now - start) / 360), eased = 1 - Math.pow(1 - t, 3); object.position.lerpVectors(from, to, eased); if (reveal && t > .48 && clone.classList.contains('hidden-card')) { clone.classList.remove('hidden-card'); clone.innerHTML = `<span class="rank">${card.rank === 'T' ? '10' : card.rank}</span><span class="suit">${card.suit}</span>`; } if (reveal) object.rotation.y = Math.PI * (1 - eased); animation.renderer.render(animation.scene, animation.camera); if (t < 1) requestAnimationFrame(tick); else { animation.scene.remove(object); clone.remove(); target.style.opacity = ''; animation.active.delete(card.id); } }; requestAnimationFrame(tick);
}
function drawAnimatedCards() {
  if(animation.round !== engine.round){animation.animated.clear();animation.hidden.clear();animation.round=engine.round;} document.querySelectorAll('.accessibility-hand .card[data-card-id]').forEach(target => { const id = target.dataset.cardId, hidden = target.classList.contains('hidden-card'), key = `${engine.shoeNumber}-${engine.round}-${id}`, wasHidden = animation.hidden.get(key); if ((!animation.animated.has(key) || (wasHidden && !hidden)) && !animation.active.has(id)) { const card = [...(engine.roundCards || [])].find(c => c.id === id) || { id, rank: target.querySelector('.rank')?.textContent || '', suit: target.querySelector('.suit')?.textContent || '', hidden }; animateClone(card, target, wasHidden && !hidden); animation.animated.add(key); } animation.hidden.set(key, hidden); }); animation.renderer.render(animation.scene, animation.camera);
}
function cardHTML(c) { return `<div class="card ${['♥','♦'].includes(c.suit) ? 'red ' : ''}${c.hidden ? 'hidden-card' : ''}" data-card-id="${c.id}" aria-label="${c.hidden ? 'Face-down card' : c.rank + c.suit}">${c.hidden ? '<span class="back-mark">♠</span>' : `<span class="rank">${c.rank === 'T' ? '10' : c.rank}</span><span class="suit">${c.suit}</span>`}</div>`; }
function handHTML(h, active = false) { return `<div class="hand-wrap ${active ? 'active' : ''}"><div class="hand accessibility-hand">${h.cards.map(cardHTML).join('')}</div><div class="outcome">${h.cards.some(c => c.hidden) ? 'HOLE CARD HIDDEN' : total(h.cards)}${h.outcome ? ' · ' + h.outcome.toUpperCase() : ''}</div></div>`; }
function saveStats() { try { localStorage.setItem('opp-trainer-stats', JSON.stringify(stats)); } catch {} }
function settleMoney() {
  const key = `${money.sessionId}:${engine.round}`;
  if (engine.phase !== 'round-complete' || money.ledger.some(x => x.key === key)) return;
  const net = engine.netProfit - money.netProfit; money = { ...money, bankroll: engine.bankroll, netProfit: engine.netProfit, lastRoundNet: net, ledger: [{ key, round: engine.round, shoe: engine.shoeNumber, net, balance: engine.bankroll }, ...money.ledger].slice(0, 20) }; saveBankroll(localStorage, money);
}
function persist() { settleMoney(); saveSnapshot(localStorage, { engine, graded, quizTarget, stats }); }
function renderMoney() { $('#bankroll').textContent = `${money.bankroll.toLocaleString()} chips`; $('#session-profit').textContent = `${signed(money.netProfit)} chips`; $('#last-round-net').textContent = money.ledger.length ? `${signed(money.lastRoundNet)} chips` : '—'; $('#available-value').textContent = Math.max(0, money.bankroll - (engine.phase === 'playing' ? (engine.committed || 0) : 0)).toLocaleString(); $('#money-history').innerHTML = money.ledger.length ? money.ledger.map(x => `<div class="history-row"><span>Round ${x.round}</span><span class="${x.net >= 0 ? 'ok' : 'bad'}">${signed(x.net)} · ${x.balance} chips</span></div>`).join('') : '<p class="muted">Settled rounds appear here. Active stakes are held, not yet settled.</p>'; }
function render() {
  settleMoney(); $('#rc').textContent = engine.phase === 'ready' ? '+6' : graded ? signed(engine.runningCount) : '?'; $('#cards-left').textContent = `${engine.shoe.length} · ${engine.decksRemaining.toFixed(2)}D`; $('#round').textContent = engine.round; $('#phase').textContent = engine.phase.replaceAll('-', ' ').toUpperCase(); $('#shoe-detail').textContent = `Shoe ${engine.shoeNumber || 1} · ${engine.decks * 52 - engine.shoe.length} / ${engine.decks * 52} cards dealt · cut at 75%`; $('#shoe-progress').value = engine.decks * 52 - engine.shoe.length; $('#shoe-progress').max = engine.decks * 52; $('#dealer-hand').innerHTML = engine.dealer ? handHTML(engine.dealer) : ''; $('#seats').innerHTML = engine.opponents?.map((h, i) => `<div class="other-seat"><div class="seat-title">SEAT ${i + 1}<span>AUTO · STAND 17</span></div>${handHTML(h)}</div>`).join('') || ''; $('#player-hands').innerHTML = engine.hands?.map((h, i) => `<div class="player-hand"><div class="seat-title">${engine.hands.length > 1 ? `HAND ${i + 1}` : 'PLAYER'} · ${h.bet} CHIPS${h.doubled ? ' · DOUBLE' : ''}</div>${handHTML(h, engine.phase === 'playing' && i === engine.activeIndex)}</div>`).join('') || ''; $('#bet').disabled = engine.phase === 'playing' || (engine.phase === 'round-complete' && !graded); $('#accuracy').textContent = stats.asked ? `${Math.round(stats.correct / stats.asked * 100)}%` : '—'; renderControls(); renderMoney(); drawAnimatedCards(); renderHistory(); persist(); }
function renderControls() { const c = $('#controls'); if (engine.phase === 'round-complete' && !graded) { c.innerHTML = '<span class="muted">Complete the count check below to continue ↓</span>'; return; } if (engine.phase !== 'playing') { c.innerHTML = `<button class="primary" id="deal">${engine.phase === 'ready' ? 'Deal round' : 'Deal next round'} <kbd>↵</kbd></button>`; $('#deal').onclick = startRound; return; } c.innerHTML = `<button id="hit" ${engine.canHit() ? '' : 'disabled'}>Hit <kbd>H</kbd></button><button id="stand">Stand <kbd>S</kbd></button><button id="double" ${engine.canDouble?.() ? '' : 'disabled'}>Double <kbd>D</kbd></button><button id="split" ${engine.canSplit() ? '' : 'disabled'}>Split</button>`; for (const action of ['hit', 'stand', 'double', 'split']) $('#' + action).onclick = () => { engine[action](); afterAction(); }; }
function afterAction() { if (engine.phase === 'round-complete') openQuiz(); render(); }
function startRound() { if (engine.phase === 'round-complete' && !graded) return; const bet = Number($('#bet').value); if (!Number.isInteger(bet) || bet < 1 || bet > engine.bankroll) { $('#message').textContent = 'Choose a whole-chip stake within your bankroll.'; return; } graded = false; quizTarget = null; $('#quiz').classList.add('hidden'); engine.round = Math.max(engine.round, money.roundSerial); if (!engine.startRound(bet)) return; money.roundSerial = engine.round; $('#message').textContent = 'Your move. Count low cards, subtract one for each final hand.'; afterAction(); }
function openQuiz() { quizTarget = { rc: engine.runningCount, tc: normalizedTC(engine.runningCount, engine.decksRemaining) }; $('#quiz').classList.remove('hidden'); $('#rc-answer').value = ''; $('#tc-answer').value = ''; $('#check-quiz').disabled = false; $('#quiz-result').innerHTML = ''; $('#quiz-decks').textContent = `Use ${engine.shoe.length} ÷ 52 = ${engine.decksRemaining.toFixed(6)} decks remaining (exact fraction).`; $('#message').textContent = 'Round complete. Count all final hands, including the dealer and split hands.'; $('#quiz').scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
function parseNum(v) { return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(v.trim()) ? Number(v) : null; }
function checkQuiz() { if (!quizTarget || graded) return; const rc = parseNum($('#rc-answer').value), tc = parseNum($('#tc-answer').value); if (rc === null || !Number.isInteger(rc) || tc === null) { $('#quiz-result').textContent = 'Enter a whole-number running count and numeric normalized count.'; return; } graded = true; $('#check-quiz').disabled = true; const rcOk = rc === quizTarget.rc, tcOk = Math.abs(tc - quizTarget.tc) < .051; stats.asked += 2; stats.correct += Number(rcOk) + Number(tcOk); stats.history.unshift({ round: engine.round, shoe: engine.shoeNumber, rc: rcOk, tc: tcOk }); stats.history = stats.history.slice(0, 10); saveStats(); const delta = engine.results.reduce((s, r) => s + r.delta, 0); $('#quiz-result').innerHTML = `<div class="result-head">${rcOk && tcOk ? '✓ Sharp count.' : 'Let’s break it down.'}<br>Running count: <b>${signed(quizTarget.rc)}</b> ${rcOk ? '✓' : '✕'} · Normalized exercise: <b>${quizTarget.tc.toFixed(1)}</b> ${tcOk ? '✓' : '✕'}<p>Previous RC ${signed(quizTarget.rc - delta)} + round change ${signed(delta)} = ${signed(quizTarget.rc)}.</p></div>` + engine.results.map((r, i) => `<div class="explain"><span>${r.handId === 'dealer' ? 'Dealer' : r.handId.startsWith('seat') ? 'Auto seat ' + (Number(r.handId.split('-')[1]) + 1) : 'Your hand ' + (i + 1)} · ${r.ranks.join(' ')}<br>${r.ranks.filter(x => ['2', '3', '4', '5', '6'].includes(x)).length} low cards − 1 = <b>${signed(r.delta)}</b></span><span>${r.outcome}</span></div>`).join(''); render(); }
function renderHistory() { $('#history').innerHTML = stats.history.length ? stats.history.map(x => `<div class="history-row"><span>Round ${Number(x.round)}</span><span>RC <b>${x.rc ? '✓' : '×'}</b> · TC <b>${x.tc ? '✓' : '×'}</b></span></div>`).join('') : '<p class="muted">Quiz results appear here.</p>'; }
function reset(session = false) { if (engine.phase === 'playing' && !confirm('Void this practice round, return its stake, and shuffle a new shoe?')) return; if (session && !confirm('Reset bankroll, ledger, quiz history, and start a new session?')) return; clearSnapshot(localStorage); money = session ? { bankroll: 1000, netProfit: 0, lastRoundNet: 0, ledger: [], sessionId: `session-${Date.now()}-${Math.random().toString(36).slice(2)}`, roundSerial: 0 } : money; saveBankroll(localStorage, money); engine = new BlackjackEngine({ decks: Number($('#deck-select').value), initialBankroll: money.bankroll }); engine.netProfit = money.netProfit; graded = false; quizTarget = null; $('#quiz').classList.add('hidden'); if (session) { stats = emptyStats(); saveStats(); } $('#message').textContent = 'Fresh shoe. Start the running count at +6.'; render(); }
$('#deck-select').onchange = () => reset(); $('#new-shoe').onclick = () => reset(); $('#new-session').onclick = () => reset(true); $('#clear-history').onclick = () => { stats = emptyStats(); saveStats(); render(); }; $('#check-quiz').onclick = checkQuiz; document.addEventListener('keydown', e => { if (e.target.matches('input,select,button')) return; const key = e.key.toLowerCase(); if (key === 'enter') $('#deal')?.click(); if (key === 'h') $('#hit')?.click(); if (key === 's') $('#stand')?.click(); if (key === 'd') $('#double')?.click(); });
$('#deck-select').value = String(engine.decks);
initThree(); render(); if (engine.phase === 'round-complete' && !graded) openQuiz();
